spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 100
      max-total: 500
      max-idle: 100
      max-wait-millis: 5000
      min-idle: 20
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 300000
      num-tests-per-eviction-run: 20
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    max-connections: 900
    min-spare-threads: 100
    accesslog:
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b %T'
      enabled: true
      directory: ${user.dir}/logs
      prefix: access.${HOST:127.0.0.1}.${server.port:8080}